[codestyle]
indent_type='space' # 'tab' or 'space'
indent_width=4
#template_file='~/my_template.cpp'
workspace_dir='~/workspace/AtCoder/'
lang='python' # 'cpp' or 'java' (Currently)
#code_generator_file="~/custom_code_generator.py"

[postprocess]
#exec_on_each_problem_dir='clang-format -i ./*.cpp'
#exec_on_contest_dir='touch CMakeLists.txt'

[etc]
#download_without_login=false
#parallel_download=false
#save_no_session_cache=false
