import = ["~/.config/alacritty/themes/themes/iterm.toml"]

[env]
TERM = "alacritty"

[font]
size = 15.0

[font.normal]
family = "Cica"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
startup_mode = "Maximized"
option_as_alt = "Both"

[window.padding]
x = 5
y = 0
